<a href="https://colab.research.google.com/github/ShaazCode/Python-Libraries---EDA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy - Introduction

Numpy stands for Numerical Python

We make use of numpy because it makes number calculation super fast, simple and perfect.
Numpy is used to work with the array of numbers

To work with large amounts of numbers easily and quickly.
Python lists are slow. NumPy arrays are much faster and take less memory.

Why we use array?  (array store the value of similar data types)

1. Fast
2. Memory efficient: Stores the number in compact array not in list
3. vectorized: do match on entire array at once (no loops)
4. interoperable: it can be used by any another library also
5. Powerful tools — linear algebra, random numbers, Fourier transforms, statistics.

## Core Properties

n-darray:  (1D, 2D , 3D, n-d)
All element have similar data types
Main properties: .shape, .ndim , .size, .dtype

In [1]:
import numpy as np #importing the numpy library and np is an object of an numpy library

a = [10,20,30,40,50]

# np.array() : this convert list into array

num = np.array(a)  #array is an builtin function whereas np is an object and num is an variable that will store np.array(a)
print(num)  #printing the value

[10 20 30 40 50]


## 1-D Array

1-D array is a list of a numbers, like a rows of values

In [2]:
a = [10,20,30,40,50]
num = np.array(a)
print(num)

[10 20 30 40 50]


## 2-D Array

2D array is like a table or matrix with rows and columns

In [3]:
# 2d array is a collection of rows and column so we just have to create the rows and column and at the start we have to strating brackets and at the end and each rows are seperated by comma
d2 = [[10,20,30],
      [40,50,60],
      [70,80,90]]
d2_array = np.array(d2)
print(d2_array)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## 3-Dimensional Array

3 Dimensioanl array means multiple table stacked(group) together

In [4]:
 # 2 stacked table
d3 = ([[[10,20,30],
      [40,50,60]],

      [[70,80,90],
      [11,22,33]]])

d3_array = np.array(d3)
print(d3_array)

[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [11 22 33]]]


In [5]:
# 3 stacked table

d3d = ([[[1,2,3],
      [4,5,6]],

      [[7,8,9],
      [10,11,12]],

      [[13,14,15],
      [16,17,18]]])
d3d_array = np.array(d3d)
print(d3d_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


## Array creation operations

Array creation is the first step in numpy , once we had created the array so we can perform the math operation , indexing operation and reshaping operation on it.

1. np.array()

2. np.zeros()

3. np.ones()

4. np.arange()

5. np.linspace()

6. np.eye()

7. np.random.rand()

8. np.random.randint()

1. np.array() : This convert python list into array

In [6]:
import numpy as np #importing the numpy library and np is an object of an numpy library

a = [10,20,30,40,50]

# np.array() : this convert list into array

num = np.array(a)  #array is an builtin function whereas np is an object and num is an variable that will store np.array(a)
print(num)  #printing the value

[10 20 30 40 50]


2. np.zeros(): Create an array with zeros

In [8]:
zero_array = np.zeros(5)  # 1-D array
print(zero_array)


[0. 0. 0. 0. 0.]


In [12]:
# zero with rows and columns
zero_array = np.zeros((2,3))
#np.zeros()it takes 2 parameter rows and column
# np.zeros((rows, column))
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]]
