<a href="https://colab.research.google.com/github/ShaazCode/Python-Libraries---EDA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy - Introduction

Numpy stands for Numerical Python

We make use of numpy because it makes number calculation super fast, simple and perfect.
Numpy is used to work with the array of numbers

To work with large amounts of numbers easily and quickly.
Python lists are slow. NumPy arrays are much faster and take less memory.

Why we use array?  (array store the value of similar data types)

1. Fast
2. Memory efficient: Stores the number in compact array not in list
3. vectorized: do match on entire array at once (no loops)
4. interoperable: it can be used by any another library also
5. Powerful tools — linear algebra, random numbers, Fourier transforms, statistics.

## Core Properties

n-darray:  (1D, 2D , 3D, n-d)
All element have similar data types
Main properties: .shape, .ndim , .size, .dtype

In [ ]:
import numpy as np #importing the numpy library and np is an object of an numpy library

a = [10,20,30,40,50]

# np.array() : this convert list into array

num = np.array(a)  #array is an builtin function whereas np is an object and num is an variable that will store np.array(a)
print(num)  #printing the value

[10 20 30 40 50]


## 1-D Array

1-D array is a list of a numbers, like a rows of values

In [ ]:
a = [10,20,30,40,50]
num = np.array(a)
print(num)

[10 20 30 40 50]


## 2-D Array

2D array is like a table or matrix with rows and columns

In [ ]:
# 2d array is a collection of rows and column so we just have to create the rows and column and at the start we have to strating brackets and at the end and each rows are seperated by comma
d2 = [[10,20,30],
      [40,50,60],
      [70,80,90]]
d2_array = np.array(d2)
print(d2_array)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## 3-Dimensional Array

3 Dimensioanl array means multiple table stacked(group) together

In [ ]:
 # 2 stacked table
d3 = ([[[10,20,30],
      [40,50,60]],

      [[70,80,90],
      [11,22,33]]])

d3_array = np.array(d3)
print(d3_array)

[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [11 22 33]]]


In [ ]:
# 3 stacked table

d3d = ([[[1,2,3],
      [4,5,6]],

      [[7,8,9],
      [10,11,12]],

      [[13,14,15],
      [16,17,18]]])
d3d_array = np.array(d3d)
print(d3d_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


# **Array creation operations**

Array creation is the first step in numpy , once we had created the array so we can perform the math operation , indexing operation and reshaping operation on it.

1. np.array()

2. np.zeros()

3. np.ones()

4. np.arange()

5. np.linspace()

6. np.eye()

7. np.random.rand()

8. np.random.randint()

1. np.array() : This convert python list into array

In [ ]:
import numpy as np #importing the numpy library and np is an object of an numpy library

a = [10,20,30,40,50]

# np.array() : this convert list into array

num = np.array(a)  #array is an builtin function whereas np is an object and num is an variable that will store np.array(a)
print(num)  #printing the value

[10 20 30 40 50]


2. np.zeros(): Create an array with zeros

In [ ]:
zero_array = np.zeros(5)  # 1-D array
print(zero_array)


[0. 0. 0. 0. 0.]


In [ ]:
# zero with rows and columns
zero_array = np.zeros((2,3))
#np.zeros()it takes 2 parameter rows and column
# np.zeros((rows, column))
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]]


### 3. np.ones(): Create an array with ones

In [ ]:
zeros_array = np.ones(5)
print(zeros_array)

[1. 1. 1. 1. 1.]


In [ ]:
zeros_array = np.ones((2,3))
print(zeros_array)

[[1. 1. 1.]
 [1. 1. 1.]]


### 4. np.arange(): It create an array with range (evenly spcified numbers)

In [ ]:
# arange
arange_array = np.arange(0 , 10, 2)
# np.arange(start, stop , step)
# np.arange() functions takes 3 parameter, from where to start , till where to run and the space
print(arange_array)

[0 2 4 6 8]


5. np.random().rand(): Basically it will create an array of random numbersbetween 0 to 1

In [ ]:
# Generate random number in range 100
arr = np.random.randint(100)  # it will generate only one random number inbetween 1 to 100
print(arr)


84


In [ ]:
# Generate random number in range 100
# np.random.randint() it takes 3 parameter (start -> End -> how many value to generate)
arr = np.random.randint(1, 100, 5)  # 5 random integers from 1 to 100
print(arr)


[57 76 60 67 11]


# **Arithematic operations on array**

Arithematic operations are:

addition (used to add) +

subtraction (used to substact) -

multiplication (used to multiply) *

division (used to divide) /

power (used to find square) **

modulo (return the remainder) %

In [ ]:
# addition
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# 1+4
# 2+5
# 3+6

print(a + b)


[5 7 9]


In [ ]:
# Substraction
print(a-b)

[-3 -3 -3]


In [ ]:
# Multiplication
print(a*b)

[ 4 10 18]


In [ ]:
# Division
print(a / b)

[0.25 0.4  0.5 ]


In [ ]:
# Floor division: it gives the round off value
print(a // b)

[0 0 0]


In [ ]:
# Exponentiation or power
print(a ** b)

[  1  32 729]


In [ ]:
# Module: return the remainder
print(a % b)

[1 2 3]


## Aggregation

Aggregrate function is used when we want to sumarize the array into a single value like total, average, minimum, etc

In [3]:
import numpy as np
a = [10,20,30,40,50]
np.sum(a)


np.int64(150)

In [4]:
# used to find the minimum value form the array
np.min(a)

np.int64(10)

In [5]:
# used to find the maximum value from the arrray
np.max(a)

np.int64(50)

In [6]:
# used to get the mean from the array
np.mean(a)

np.float64(30.0)

In [7]:
# used to get median from the array
np.median(a)

np.float64(30.0)

In [9]:
print("Hello")

Hello


# Indexing

Indexing is used to access or modify the array if we want some part of an array then we can take it using indexing

In [10]:
# accessing the element from particualr index position
a[1]

20

In [12]:
# accessing element from the 1st position to 3rd position
a[1:3]

[20, 30]

In [13]:
# from 1st index psoition it will start and it will go till last element
a[1:]

[20, 30, 40, 50]

In [14]:
a[:]
# it will start from zero index and it will go till last index

[10, 20, 30, 40, 50]

# Reshaping

Reshaping means changing the shape of an array without changing the data

In [ ]:
# Suppose we are having 1d array with 12 numbers and we want to change its shape(rows & column) like we want 3 rows and 4 column so we can make that.

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
